language: node_js
sudo: false
node_js:
  - "7"

before_script:
  - git submodule update --init --recursive
  - git submodule foreach "yarn && yarn build"
  - cd game-client && yarn && cd ..
  - cd frontend && yarn && cd ..

script:
  - cd game-client && yarn travis && cd ..
  - cd frontend && yarn travis && cd ..

deploy:
  - provider: script
    script: cd frontend && NODE_ENV=production yarn build && cd ..
    skip_cleanup: true
    on: master
  - provider: surge
    project: ./frontend/dist
    domain: turbo-winner.surge.sh
    skip_cleanup: true
    on: master
  - provider: heroku
    app: turbo-winner
    api_key:
      secure: mi6FCyne1258K9oNMu3+jPYCph/Y4D8aa748dRijhpvLxzUBSh7qHNO1iuR8TSg/u9l/rjGVTZvyN5Tgacb7HNApMYfZHHOUkhfOEQ8SL6MpvhWkkll2WEhvm/VGXYMdyq/cB6dIjG8G4apcleOAfBzJnAyrE7kt2AzGk3tZ5CoRujgD8/yFtqNTUYwkeOs567LDP8OqFEFQhSjLRjrorNDuPib11RrqHeQnb4fRcr0/B3tkquID4JSGJrSO7xtyy+6CL8soF5Q9Bpbj6Y9IfTdrVhnX/3Ek442De1ngichpilFC/hftU1vPXxRxBduLeCUKyuXNcUZxqESBuDBiZRAaTSRs3R38vjUniZ4tGCFKADmfG3FsMiWaA/SzuD66KzuNeQQ+MLtkmw3mh3a24fgMOLGXZaoEvylcbwYXFHW4Ob49S0XY8Twk9ZcGQ/rM2lAs35kWJof4kL74dClkks4NsT0/cI/13V4oE9Oa+ts+4swIQsrgh07Al+Wwls/EUpyM1KmpcLEZQXttske3tAaY3LU0MXJT+lMi1Tbn8w7qEzbbfESBxHCIeDae2fvy0aHIu8dvAclp9miabsQ4JrWH8NRIoihLiIsPCDDCAJAnk1X/LiuyaIa5bdAoMtne2G127payllXEOGG1n6SG2NcStVcgez+QYmJrCaqYlzU=
    skip_cleanup: true
    on: master
